export enum Routes {
  Intro = 'Intro',
  Login = 'Login',
  Welcome = 'Welcome',
  Home = 'Home',
  Notifications = 'Notifications',
  NotificationsStack = 'NotificationsStack',
  Favorites = 'Favorites',
  Library = 'Library',
  MyBooks = 'MyBooks',
  MyBook = 'MyBook',
  MyBookRead = 'MyBookRead',
  LibraryStack = 'LibraryStack',
  LibraryProduct = 'LibraryProduct',
  LibraryProductRead = 'LibraryProductRead',
  LibraryProductSave = 'LibraryProductSave',
  UserProfile = 'UserProfile',
  Details = 'Details',
  News = 'News',
  Museum = 'Museum',
  MuseumStack = 'MuseumStack',
  AboutMuseum = 'AboutMuseum',
  IntroMuseum = 'IntroMuseum',
  TimeWork = 'TimeWork',
  Centre = 'Centre',
  Tour = 'Tour',
  TourPages = 'TourPages',

  // Bottom Navigator
  BottomNavigator = 'BottomNavigator',
}
