export enum Routes {
  Intro = 'Intro',
  Login = 'Login',
  Welcome = 'Welcome',
  Home = 'Home',
  AuthStack = 'AuthStack',
  CustomDrawer = 'CustomDrawer',

  Notifications = 'Notifications',
  NotificationsStack = 'NotificationsStack',
  Favorites = 'Favorites',
  Library = 'Library',
  MyBooks = 'MyBooks',
  MyBook = 'MyBook',
  MyBookRead = 'MyBookRead',
  LibraryStack = 'LibraryStack',
  LibraryProduct = 'LibraryProduct',
  LibraryProductRead = 'LibraryProductRead',
  LibraryProductSave = 'LibraryProductSave',
  UserProfile = 'UserProfile',
  Details = 'Details',
  News = 'News',

  Centre = 'Centre',
  CentreStack = 'CentreStack',
  AboutCentre = 'AboutCentre',
  TasksCentre = 'TasksCentre',
  AdviceCentre = 'AdviceCentre',
  StaffCentre = 'StaffCentre',
  StaffCard = 'StaffCard',
  Documents = 'Documents',
  Media = 'Media',
  Movie = 'Movie',
  Audio = 'Audio',
  Photo = 'Photo',

  Museum = 'Museum',
  MuseumStack = 'MuseumStack',
  AboutMuseum = 'AboutMuseum',
  IntroMuseum = 'IntroMuseum',
  TimeWork = 'TimeWork',
  Tour = 'Tour',
  TourPages = 'TourPages',

  // Bottom Navigator
  BottomNavigator = 'BottomNavigator',
}
